-- Auto-generated from KH3 Archipelago
--
-- Items the pack does not display are deliberately absent: mapping them made
-- the autotracker log 'Did not find object for code ...' on every seed without
-- doing anything. Their names and codes are parked in
-- scripts/tools/unmapped_item_codes.json; move an entry back here when its
-- item is added to items/items.json.

ITEM_MAPPING_BY_NAME = {
    ["Ability: Air Slide"] = { code = "ability_air_slide", type = "toggle" },
    ["Ability: Withstand Combo"] = { code = "ability_withstand_combo", type = "toggle" },
    ["Ability: Combo Master"] = { code = "ability_combo_master", type = "toggle" },
    ["Ability: Dodge Roll"] = { code = "ability_dodge_roll", type = "toggle" },
    ["Ability: Doubleflight"] = { code = "ability_doubleflight", type = "toggle" },
    ["Ability: Glide"] = { code = "ability_glide", type = "toggle" },
    ["Ability: Counter Slash"] = { code = "ability_counter_slash", type = "toggle" },
    ["Ability: High Jump"] = { code = "ability_high_jump", type = "toggle" },
    ["Ability: Second Chance"] = { code = "ability_second_chance", type = "toggle" },
    ["Ability: Leaf Bracer"] = { code = "ability_leaf_bracer", type = "toggle" },
    ["Ability: Pole Spin"] = { code = "ability_pole_spin", type = "toggle" },
    ["Ability: Block"] = { code = "ability_block", type = "toggle" },
    ["Ability: Counter Kick"] = { code = "ability_counter_kick", type = "toggle" },
    ["Ability: Superjump"] = { code = "ability_superjump", type = "toggle" },
    ["Ability: Wall Kick"] = { code = "ability_wall_kick", type = "toggle" },
    ["Gummiphone"] = { code = "gummiphone", type = "toggle" },
    ["Dream Heartbinder"] = { code = "dream_heartbinder", type = "toggle" },
    ["Pixel Heartbinder"] = { code = "pixel_heartbinder", type = "toggle" },
    ["'Ohana Heartbinder"] = { code = "ohana_heartbinder", type = "toggle" },
    ["Pride Heartbinder"] = { code = "pride_heartbinder", type = "toggle" },
    ["Ocean Heartbinder"] = { code = "ocean_heartbinder", type = "toggle" },
    ["Proof of Fantasy"] = { code = "proof_of_fantasy", type = "toggle" },
    ["Proof of Promises"] = { code = "proof_of_promises", type = "toggle" },
    ["Proof of Times Past"] = { code = "proof_of_times_past", type = "toggle" },
    ["Heart Piece"] = { code = "heart_piece", type = "consumable" },
    ["Magic: Aero"] = { code = "aero", type = "consumable" },
    ["Magic: Blizzard"] = { code = "blizzard", type = "consumable" },
    ["Magic: Cure"] = { code = "cure", type = "consumable" },
    ["Magic: Fire"] = { code = "fire", type = "consumable" },
    ["Magic: Thunder"] = { code = "thunder", type = "consumable" },
    ["Magic: Water"] = { code = "water", type = "consumable" },
    ["Secret Report 1"] = { code = "secret_report", type = "consumable" },
    ["Secret Report 2"] = { code = "secret_report", type = "consumable" },
    ["Secret Report 3"] = { code = "secret_report", type = "consumable" },
    ["Secret Report 4"] = { code = "secret_report", type = "consumable" },
    ["Secret Report 5"] = { code = "secret_report", type = "consumable" },
    ["Secret Report 6"] = { code = "secret_report", type = "consumable" },
    ["Secret Report 7"] = { code = "secret_report", type = "consumable" },
    ["Secret Report 8"] = { code = "secret_report", type = "consumable" },
    ["Secret Report 9"] = { code = "secret_report", type = "consumable" },
    ["Secret Report 10"] = { code = "secret_report", type = "consumable" },
    ["Secret Report 11"] = { code = "secret_report", type = "consumable" },
    ["Secret Report 12"] = { code = "secret_report", type = "consumable" },
    ["Secret Report 13"] = { code = "secret_report", type = "consumable" },
    -- Sent once per shard; a single AP item name repeated up to the seed's
    -- Ultima Weapon Shard Count (2-13), not 13 distinct numbered items.
    ["Ultima Weapon Shard"] = { code = "ultima_weapon_shard", type = "consumable" },
    -- Other Ultima Weapon unlock modes (shop/yozora/randomized pool) send the
    -- keyblade itself instead of shards; fill the same counter to max so one
    -- widget reflects "Ultima obtained" regardless of the seed's unlock mode.
    ["Ultima Weapon"] = { code = "ultima_weapon_shard", type = "consumable_max", max = 13 },

    -- Logic items (portal keyblades, unlocks, movement abilities)
    ["Hero's Origin"] = { code = "kb_heros_origin", type = "toggle" },
    ["Favorite Deputy"] = { code = "kb_favorite_deputy", type = "toggle" },
    ["Happy Gear"] = { code = "kb_happy_gear", type = "toggle" },
    ["Ever After"] = { code = "kb_ever_after", type = "toggle" },
    ["Wheel of Fate"] = { code = "kb_wheel_of_fate", type = "toggle" },
    ["Crystal Snow"] = { code = "kb_crystal_snow", type = "toggle" },
    ["Nano Gear"] = { code = "kb_nano_gear", type = "toggle" },
    ["Shooting Star"] = { code = "kb_shooting_star", type = "toggle" },
    ["Kingdom Key"] = { code = "kingdom_key", type = "toggle" },
    ["Classic Tone"] = { code = "kb_classic_tone", type = "toggle" },
    ["Oblivion"] = { code = "kb_oblivion", type = "toggle" },
    ["Oathkeeper"] = { code = "kb_oathkeeper", type = "toggle" },
    ["Unlock: Wall Run"] = { code = "unlock_wall_run", type = "toggle" },
    ["Unlock: Magic"] = { code = "unlock_magic", type = "toggle" },
    ["Unlock: Attraction Flow"] = { code = "unlock_attraction_flow", type = "toggle" },
    ["Unlock: Airstep"] = { code = "unlock_airstep", type = "toggle" },
    ["Unlock: Style Change"] = { code = "unlock_style_change", type = "toggle" },
    -- Classic Kingdom minigame unlocks. Each "<game> - High Score" check is
    -- gated on its own game, and "Complete All Games" on all 23 (Rules.py).
    ["CK: Giantland"] = { code = "ck_giantland", type = "toggle" },
    ["CK: Mickey, The Mail Pilot"] = { code = "ck_mickey_the_mail_pilot", type = "toggle" },
    ["CK: The Musical Farmer"] = { code = "ck_the_musical_farmer", type = "toggle" },
    ["CK: Building a Building"] = { code = "ck_building_a_building", type = "toggle" },
    ["CK: The Mad Doctor"] = { code = "ck_the_mad_doctor", type = "toggle" },
    ["CK: Mickey's Kitten Catch"] = { code = "ck_mickeys_kitten_catch", type = "toggle" },
    ["CK: The Klondike Kid"] = { code = "ck_the_klondike_kid", type = "toggle" },
    ["CK: Fishin' Frenzy"] = { code = "ck_fishin_frenzy", type = "toggle" },
    ["CK: The Karnival Kid"] = { code = "ck_the_karnival_kid", type = "toggle" },
    ["CK: Mickey Cuts Up"] = { code = "ck_mickey_cuts_up", type = "toggle" },
    ["CK: Mickey's Prison Escape"] = { code = "ck_mickeys_prison_escape", type = "toggle" },
    ["CK: How to Play Baseball"] = { code = "ck_how_to_play_baseball", type = "toggle" },
    ["CK: How to Play Golf"] = { code = "ck_how_to_play_golf", type = "toggle" },
    ["CK: Mickey's Circus"] = { code = "ck_mickeys_circus", type = "toggle" },
    ["CK: Camping Out"] = { code = "ck_camping_out", type = "toggle" },
    ["CK: Taxi Troubles"] = { code = "ck_taxi_troubles", type = "toggle" },
    ["CK: Beach Party"] = { code = "ck_beach_party", type = "toggle" },
    ["CK: The Wayward Canary"] = { code = "ck_the_wayward_canary", type = "toggle" },
    ["CK: Mickey's Mechanical Man"] = { code = "ck_mickeys_mechanical_man", type = "toggle" },
    ["CK: The Barnyard Battle"] = { code = "ck_the_barnyard_battle", type = "toggle" },
    ["CK: Cast Out to Sea"] = { code = "ck_cast_out_to_sea", type = "toggle" },
    ["CK: Backyard Sports"] = { code = "ck_backyard_sports", type = "toggle" },
    ["CK: Mickey Steps Out"] = { code = "ck_mickey_steps_out", type = "toggle" },
    -- Party member unlocks. Always in the pool (PARTY_MEMBER_UNLOCK_EXTRA_ITEM_POOL_ITEMS),
    -- classified "useful"; no logic rule references them.
    ["Party Member: Donald"] = { code = "party_donald", type = "toggle" },
    ["Party Member: Goofy"] = { code = "party_goofy", type = "toggle" },
    ["Party Member: Donald (Toy Box)"] = { code = "party_donald_toy_box", type = "toggle" },
    ["Party Member: Goofy (Toy Box)"] = { code = "party_goofy_toy_box", type = "toggle" },
    ["Party Member: Donald (Monstropolis)"] = { code = "party_donald_monstropolis", type = "toggle" },
    ["Party Member: Goofy (Monstropolis)"] = { code = "party_goofy_monstropolis", type = "toggle" },
    ["Party Member: Donald (Caribbean)"] = { code = "party_donald_caribbean", type = "toggle" },
    ["Party Member: Goofy (Caribbean)"] = { code = "party_goofy_caribbean", type = "toggle" },
    ["Party Member: Hercules"] = { code = "party_hercules", type = "toggle" },
    ["Party Member: Woody"] = { code = "party_woody", type = "toggle" },
    ["Party Member: Buzz Lightyear"] = { code = "party_buzz_lightyear", type = "toggle" },
    ["Party Member: Rapunzel"] = { code = "party_rapunzel", type = "toggle" },
    ["Party Member: Flynn Rider"] = { code = "party_flynn_rider", type = "toggle" },
    ["Party Member: Sulley"] = { code = "party_sulley", type = "toggle" },
    ["Party Member: Mike"] = { code = "party_mike", type = "toggle" },
    ["Party Member: Captain Jack Sparrow"] = { code = "party_captain_jack_sparrow", type = "toggle" },
    ["Party Member: Baymax"] = { code = "party_baymax", type = "toggle" },
    ["Party Member: Mickey"] = { code = "party_mickey", type = "toggle" },
    ["Party Member: Riku"] = { code = "party_riku", type = "toggle" },
    ["Party Member: Aqua"] = { code = "party_aqua", type = "toggle" },
    ["Party Member: Ventus"] = { code = "party_ventus", type = "toggle" },
    ["Party Member: Lea"] = { code = "party_lea", type = "toggle" },
    ["Party Member: Kairi"] = { code = "party_kairi", type = "toggle" },
    ["Party Member: Roxas"] = { code = "party_roxas", type = "toggle" },
    ["Party Member: Xion"] = { code = "party_xion", type = "toggle" },
    -- Per-keyblade Style Change unlocks, added when the seed uses
    -- style_change: keybladestylesanity. Classified progression by AP,
    -- though no access rule references them.
    ["Unlock Style: Kingdom Key"] = { code = "style_kingdom_key", type = "toggle" },
    ["Unlock Style: Shooting Star"] = { code = "style_shooting_star", type = "toggle" },
    ["Unlock Style: Hero's Origin"] = { code = "style_heros_origin", type = "toggle" },
    ["Unlock Style: Favorite Deputy"] = { code = "style_favorite_deputy", type = "toggle" },
    ["Unlock Style: Ever After"] = { code = "style_ever_after", type = "toggle" },
    ["Unlock Style: Wheel of Fate"] = { code = "style_wheel_of_fate", type = "toggle" },
    ["Unlock Style: Crystal Snow"] = { code = "style_crystal_snow", type = "toggle" },
    ["Unlock Style: Nano Gear"] = { code = "style_nano_gear", type = "toggle" },
    ["Unlock Style: Happy Gear"] = { code = "style_happy_gear", type = "toggle" },
    ["Unlock Style: Classic Tone"] = { code = "style_classic_tone", type = "toggle" },
    ["Unlock Style: Oathkeeper"] = { code = "style_oathkeeper", type = "toggle" },
    ["Unlock Style: Oblivion"] = { code = "style_oblivion", type = "toggle" },
    ["Unlock Style: Ultima Weapon"] = { code = "style_ultima_weapon", type = "toggle" },
    ["Unlock Style: Grand Chef"] = { code = "style_grand_chef", type = "toggle" },
    ["Unlock Style: Hunny Spout"] = { code = "style_hunny_spout", type = "toggle" },
    ["Unlock Style: Starlight"] = { code = "style_starlight", type = "toggle" },
    ["Unlock Style: Pandora's Power"] = { code = "style_pandoras_power", type = "toggle" },
    -- Non-portal keyblades: obtainable but not tied to a world gate.
    ["Grand Chef"] = { code = "kb_grand_chef", type = "toggle" },
    ["Hunny Spout"] = { code = "kb_hunny_spout", type = "toggle" },
    ["Starlight"] = { code = "kb_starlight", type = "toggle" },
}
